#mysqlserver: "10.1.1.1:3306"
mysqlserver: "127.0.0.1:5000"
mysqluser: "user"
mysqldb: "database"
mysqlpw: "password"
influxdbhost: "http://10.1.1.2:8086"
influxdbdatabase: "database"
influxdbuser: ""
influxdbpassword: ""
sshaddr: "10.1.1.1:22"
localaddr: "127.0.0.1:5000"
remoteaddr: "127.0.0.1:3306"
usesshtunnel: false
discordtoken: ""